apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinitions
metadata:
  name: pvcbackup.djeebus.net
spec:
  scope: Cluster
  group: djeebus.net
  names:
    kind: PVCBackupConfig
    plural: pvcbackupconfigs
    singular: pvcbackupconfig
    shortNames:
      - pbts
      - pbt
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
